# Generated by Django 4.0.3 on 2022-04-12 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('rooms', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('area', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
                ('con_name', models.CharField(max_length=1000)),
                ('con_email', models.CharField(max_length=1000)),
                ('con_phn', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
