# Generated by Django 4.0.3 on 2022-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_proparty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proparty',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
