# Generated by Django 4.0.3 on 2022-04-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_cover',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='user',
        ),
    ]
